name: CVTools
main: org.cubeville.cvtools.CVTools
authors: [KipperOrigin,FrediW]
version: 0.5
api-version: 1.15

depend: [WorldEdit,WorldGuard]

commands:
  cvtools:
    description: CVTools Base Command
    permission: cvtools.commands
  cvtoolstest:
    description: CVTools Test Command
    permission: cvtools.testcommand
  ping:
    description: Command of utmost importance.
    permission: cvtools.ping
  clear:
    description: Clears one's inventory.
    permission: cvtools.clear.use
  more:
    description: Increases the number of items in the player's main hand to its maximum stack size.
    permission: cvtools.more
  item:
    description: Alias of the default Minecraft /give command.
    permission: cvtools.item
    aliases: i
  time:
    description: Check the time.
    permission: cvtools.time
  weather:
    description: Change the weather.
    permission: cvtools.weather
  shock:
    description: Shock a player.
    permission: cvtools.shock

permissions:
  
  cvtools.*:
    description: Unlimited use of cvtools commands
    default: op
    children:
      cvtools.commands: true
      cvtools.unlimited: true
      cvtools.checkentities: true
      cvtools.checksign: true
      cvtools.delay: true
      cvtools.setblocks: true
      cvtools.stopwatch: true
  cvtools.standard:
    description: Permission for standard command
    default: op
    children:
      cvtools.checkentities: true
      cvtools.checksign: true
      cvtools.commands: true
      cvtools.stopwatch: true
  cvtools.commands:
    description: Base permission for cvtools command
    default: op
  cvtools.unlimited:
    description: Removes some block count limits
    default: op
  cvtools.checkentities:
    description: Permission for the checkentities subcommand
    default: op
  cvtools.checksign:
    description: Permission for the checksign subcommand
    default: op
  cvtools.delay:
    description: Permission for the delay subcommand
    default: op
  cvtools.setblocks:
    description: Set blocks in worldguard region to specific type
    default: op
  cvtools.stopwatch:
    description: Use stopwatch in game.
    default: op
  cvtools.ping:
    description: Permission to use the /ping command
    default: true
  cvtools.clear.*:
    description: Permission to use all the /clear commands and subcommands
    default: op
    children:
      cvtools.clear.use: true
      cvtools.clear.all: true
      cvtools.clear.slot: true
      cvtools.clear.other: true
  cvtools.clear.use:
    description: Permission to use the /clear command
    default: op
  cvtools.clear.all:
    description: Permission to use the /clear -a subcommand
    default: op
  cvtools.clear.slot:
    description: Permission to use the /clear -s subcommand
    default: op
  cvtools.clear.other:
    description: Permission to use the /clear <player> subcommand
    default: op
  cvtools.more:
    description: Permission to use the /more command
    default: op
  cvtools.item:
    description: Permission to use the /item command
    default: op
  cvtools.item.other:
    description: Permission to use the /item command to give items to other players
    default: op
  cvtools.item.unlimited:
    description: Permission to use the /item command with more than 5 stacks worth of materials
    default: op
  cvtools.time:
    description: Permission to use the /time command
    default: true
  cvtools.weather:
    description: Permission to use the /weather command
    default: op
  cvtools.weather.silent:
    description: Permission to make the /weather command silent
    default: op
  cvtools.weather.duration:
    description: Permission to specify the duration of the weather event in the /weather command
    default: op
  cvtools.weather.world:
    description: Permission to specify the world in the /weather command
    default: op
  cvtools.shock:
    description: Permission to use the /shock command
    default: op
